language: csharp

sudo: false  # use the new container-based Travis infrastructure

install:
  - nvm install 6
  - nvm install -g yarn
  - npm install --global elm

script: 
  - ./build.sh Build
  - ./frontend/build.sh